apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: influxdbdeployment 
spec:
  replicas: 1 # tells deployment to run 2 pods matching the template  
  selector: 
    matchLabels: 
      app: influxdbapp
  template: 
    metadata: 
      labels: 
        app: influxdbapp
    spec: 
      containers: 
      - name: influxdbapp
        image: influxdb
        imagePullPolicy: Never
        ports: 
        - containerPort: 8086 
