apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-influx
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-influx
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce