apiVersion: v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Service 
metadata:
  name: mysqlapp 
spec: 
  selector: 
    app: mysqlapp
  type: ClusterIP
  #clusterIP: 10.99.99.99
  ports:
   - port: 3306
     targetPort: 3306



