CREATE USER 'admin'@'%' IDENTIFIED BY 'admin';
CREATE DATABASE IF NOT EXISTS `phpmyadmin`   DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;
GRANT ALL PRIVILEGES  ON *.* TO 'admin'@'%';
FLUSH PRIVILEGES;
