apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: grafanadeployment 
spec: 
  selector: 
    matchLabels:
      app: grafana 
  replicas: 1 # tells deployment to run 1 pods matching the template 
  template: 
    metadata: 
      labels: 
        app: grafana 
    spec: 
      containers: 
      - name: grafana
        image: grafana
        imagePullPolicy: Never
        ports: 
        - containerPort: 3000
        livenessProbe:
          exec:
            command:
            - sh
            - grafana_check.sh
          initialDelaySeconds: 45
          periodSeconds: 5

---
apiVersion: v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Service 
metadata:
  name: grafana 
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec: 
  selector: 
    app: grafana 
  ports:
    - port: 3000
      name: tcp
      targetPort: 3000
  type: LoadBalancer