apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: nginxeployment 
spec: 
  selector: 
    matchLabels: 
      app: nginx 
  replicas: 1 # tells deployment to run 2 pods matching the template 
  template: 
    metadata: 
      labels: 
        app: nginx 
    spec: 
      containers: 
      - name: nginx
        image: nginx
        imagePullPolicy: Never
        ports: 
        - containerPort: 80 
        - containerPort: 443 
        - containerPort: 22

---

apiVersion: v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Service 
metadata:
  name: nginx 
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec: 
  selector: 
    app: nginx 
  ports:
    - port: 80
      name: http
      targetPort: 80 
    - port: 443
      name: https
      targetPort: 443
    - port: 22
      name: ssh
      targetPort: 22
  type: LoadBalancer