apiVersion: v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Service 
metadata:
  name: nginx 
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec: 
  selector: 
    app: nginx 
  ports:
    - port: 80
      name: http
      targetPort: 80 
    - port: 443
      name: https
      targetPort: 443
    - port: 22
      name: ssh
      targetPort: 22
  type: LoadBalancer