apiVersion: v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Service 
metadata:
  #annotations:
   # metallb.universe.tf/allow-shared-ip: shared
  name: nginx 
spec: 
  selector: 
    app: nginx 
  ports:
    - port: 80
      name: http
      targetPort: 80 
    - port: 443
      name: https
      targetPort: 443
  type: LoadBalancer