apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: phpmyadminployment 
spec: 
  selector: 
    matchLabels: 
      app: phpmyadmin 
  replicas: 1  
  template: 
    metadata: 
      labels: 
        app: phpmyadmin 
    spec: 
      containers: 
      - name: phpmyadmin
        image: phpmyadmin
        imagePullPolicy: Never
        ports: 
        - containerPort: 5000

---
apiVersion: v1 
kind: Service 
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec: 
  selector: 
    app: phpmyadmin
  ports:
    - port: 5000
      name: tcp
      targetPort: 5000
  type: LoadBalancer