apiVersion: v1 
kind: Service 
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: phpmyadmin
spec: 
  selector: 
    app: phpmyadmin
  ports:
    - port: 80
      name: http
      targetPort: 80 
  type: LoadBalancer