apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: wdpdeployment 
spec:
  replicas: 1 # tells deployment to run 2 pods matching the template  
  selector: 
    matchLabels: 
      app: wordpress
  template: 
    metadata: 
      labels: 
        app: wordpress
    spec: 
      containers: 
      - name: wordpress
        image: wordpress
        imagePullPolicy: Never
        ports: 
        - containerPort: 5050 
        livenessProbe:
          exec:
            command:
            - sh
            - wordpress_check.sh
          initialDelaySeconds: 45
          periodSeconds: 5

---
apiVersion: v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Service 
metadata:
  name: wordpress 
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec: 
  selector: 
    app: wordpress
  clusterIP: 10.97.118.10
  ports:
   - port: 5050
     targetPort: 5050
  type: LoadBalancer


