apiVersion: v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Service 
metadata:
  name: wordpress 
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec: 
  selector: 
    app: wordpress
  clusterIP: 10.97.118.10
  ports:
   - port: 5050
     targetPort: 5050
  type: LoadBalancer


