apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: ftpsdeployment 
spec: 
  replicas: 1 # tells deployment to run 2 pods matching the template 
  selector: 
    matchLabels: 
      app: ftps 
  template: 
    metadata: 
      labels: 
        app: ftps 
    spec: 
      containers: 
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports: 
        - containerPort: 21
        - containerPort: 6000
        - containerPort: 6001
        - containerPort: 6002
        - containerPort: 6003
        livenessProbe:
          exec:
            command:
            - sh
            - ftps_check.sh
          initialDelaySeconds: 45
          periodSeconds: 5

---

apiVersion: v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Service 
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec: 
  selector: 
    app: ftps
  type: LoadBalancer
  ports:
    - port: 21
      targetPort: 21
      name: ftps-port0
    - port: 6000
      name: ftps-port1
      targetPort: 6000
    - port: 6001
      name: ftps-port2
      targetPort: 6001
    - port: 6002
      name: ftps-port3
      targetPort: 6002
    - port: 6003
      name: ftps-port4
      targetPort: 6003

